import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowLeft, FileText, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";

const TermsOfService = () => {
  const navigate = useNavigate();
  const [lang, setLang] = useState<"zh" | "en">("zh");

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const sections = [
    {
      title: "1. 服务协议的接受",
      enTitle: "1. Acceptance of Terms",
      body: "欢迎使用 NEXUS LAB。本服务条款（以下简称「条款」）是您与 NEXUS LAB 之间关于使用本网站、移动应用及相关服务（以下简称「服务」）的具有法律约束力的协议。注册、访问或使用本服务，即表示您已阅读、理解并同意受本条款约束。",
      enBody:
        "Welcome to NEXUS LAB. These Terms of Service (the \"Terms\") form a legally binding agreement between you and NEXUS LAB regarding your use of the website, mobile applications, and related services (the \"Service\"). By registering, accessing, or using the Service, you acknowledge that you have read, understood, and agree to be bound by these Terms.",
    },
    {
      title: "2. 服务描述",
      enTitle: "2. Description of Service",
      body: "NEXUS LAB 提供 AI 创作工具（如文本生成图片、视频、音乐、代码等）及相关的产品能力。我们保留随时修改、暂停或终止部分或全部服务的权利，重大变更时会尽量提前通知。服务的具体功能以当时实际提供的为准。",
      enBody:
        "NEXUS LAB provides AI creation tools (such as text-to-image, text-to-video, music, and code generation) and related product capabilities. We reserve the right to modify, suspend, or terminate part or all of the Service at any time, and will endeavor to give advance notice of material changes. Specific features are subject to what is actually provided at the time.",
    },
    {
      title: "3. 账户注册与安全",
      enTitle: "3. Account Registration and Security",
      body: "使用部分功能可能需要您注册账户。您应提供真实、准确、完整的注册信息，并对账户密码的保密性负责。若发现未经授权使用账户的情况，请立即通知我们。因您保管不善导致的损失，我们不承担责任。您不得为他人代为注册或转让账户。",
      enBody:
        "Some features may require account registration. You must provide true, accurate, and complete registration information and are responsible for keeping your password confidential. If you notice any unauthorized use of your account, notify us immediately. We are not liable for losses caused by your failure to safeguard your account. You may not register on behalf of others or transfer your account.",
    },
    {
      title: "4. 用户内容",
      enTitle: "4. User Content",
      body: "您通过本服务上传、输入、生成、发布的内容（包括提示词、图片、音频、视频、代码等，以下简称「用户内容」）归您或相应权利人所有。您授予我们非独占、全球、免费、可转授权的许可，以便我们存储、展示、处理和维护这些内容以提供和改进服务。您声明您拥有提交这些内容的权利且不侵犯任何第三方权益。",
      enBody:
        "Content you upload, input, generate, or publish through the Service (including prompts, images, audio, video, code, etc., \"User Content\") belongs to you or the respective rights holder. You grant us a non-exclusive, worldwide, royalty-free, sublicensable license to store, display, process, and maintain such content to provide and improve the Service. You represent that you have the rights to submit this content and that it does not infringe any third-party rights.",
    },
    {
      title: "5. AI 生成内容的知识产权",
      enTitle: "5. IP of AI-Generated Content",
      body: "对于由本服务 AI 工具生成的内容，在适用法律允许的范围内，相关权利归属于您，前提是您遵守本条款且内容不违反法律法规。我们不主张对您合法生成内容的所有权。部分生成结果可能受第三方模型或训练数据的影响，相关权利按其许可执行。",
      enBody:
        "For content generated by the Service's AI tools, to the extent permitted by applicable law and provided you comply with these Terms and applicable law, the relevant rights belong to you. We do not claim ownership of content you legitimately generate. Some outputs may be influenced by third-party models or training data, whose rights are governed by their respective licenses.",
    },
    {
      title: "6. 付费与订阅",
      enTitle: "6. Fees and Subscriptions",
      body: "本服务当前为免费提供。若我们未来推出付费功能、订阅或虚拟资源，相关价格、计费周期与退款规则将在购买前明确展示，并以届时单独的付费条款为准。除法律法规另有规定外，已支付的费用原则上不予退还。",
      enBody:
        "The Service is currently provided free of charge. If we introduce paid features, subscriptions, or virtual resources in the future, the prices, billing cycles, and refund rules will be clearly presented before purchase and governed by separate paid terms at that time. Except as required by law, fees paid are generally non-refundable.",
    },
    {
      title: "7. 可接受使用",
      enTitle: "7. Acceptable Use",
      body: "您不得利用本服务从事以下行为：上传或生成违反法律法规、侵犯他人权益的内容；生成含有歧视、暴力、色情、骚扰或虚假信息的内容；试图破解、反向工程或干扰服务正常运行；滥用资源或进行任何欺诈行为。我们有权对违规内容不予处理或删除，并限制相关账户。",
      enBody:
        "You may not use the Service to: upload or generate content that violates laws or infringes others' rights; generate content containing discrimination, violence, pornography, harassment, or false information; attempt to crack, reverse-engineer, or disrupt the Service; or abuse resources or engage in fraud. We may refuse to process or may remove violating content and restrict related accounts.",
    },
    {
      title: "8. 第三方服务",
      enTitle: "8. Third-Party Services",
      body: "本服务可能集成第三方服务（如 Agnes AI、Google 登录、QQ 邮箱、腾讯云 CloudBase 等）。您使用此类功能时，还须遵守相应第三方的服务条款与隐私政策。我们对第三方服务的内容、可用性或行为不承担责任。",
      enBody:
        "The Service may integrate third-party services (such as Agnes AI, Google sign-in, QQ Mail, Tencent CloudBase, etc.). When using such features, you are also subject to the respective third party's terms and privacy policies. We are not responsible for the content, availability, or conduct of third-party services.",
    },
    {
      title: "9. 免责声明",
      enTitle: "9. Disclaimers",
      body: "本服务按「现状」和「可用性」基础提供，我们不保证服务完全无中断、及时、安全或无错误。对于因网络、第三方服务、不可抗力或您自身原因造成的损失，我们不承担责任。AI 生成内容可能存在偏差或错误，仅供您参考和辅助创作，不应作为专业建议。",
      enBody:
        "The Service is provided on an \"as is\" and \"as available\" basis. We do not guarantee that the Service will be uninterrupted, timely, secure, or error-free. We are not liable for losses caused by networks, third-party services, force majeure, or your own actions. AI-generated content may contain bias or errors and is for reference and assistance only, not professional advice.",
    },
    {
      title: "10. 责任限制",
      enTitle: "10. Limitation of Liability",
      body: "在法律允许的最大范围内，NEXUS LAB 对任何间接、附带、特殊或惩罚性损害赔偿不承担责任，无论该责任基于合同、侵权还是其他理由。我们对您因使用本服务产生的总赔偿责任不超过您在前十二个月内向本服务支付的实际费用（如为免费使用，则以零为限）。",
      enBody:
        "To the maximum extent permitted by law, NEXUS LAB is not liable for any indirect, incidental, special, or consequential damages, whether based on contract, tort, or otherwise. Our total aggregate liability to you for using the Service shall not exceed the actual fees you paid in the preceding twelve months (or zero if the Service is free).",
    },
    {
      title: "11. 服务限制与终止",
      enTitle: "11. Suspension and Termination",
      body: "我们有权根据自身判断，对违反本条款、滥用服务或存在安全风险的用户采取限制、暂停或终止服务的措施。您也可以随时停止使用并注销账户。终止后，您的内容将按隐私政策处理，未使用的付费权益（如有）按当时付费条款执行。",
      enBody:
        "We may, at our discretion, restrict, suspend, or terminate the Service for users who violate these Terms, abuse the Service, or pose security risks. You may also stop using the Service and delete your account at any time. Upon termination, your content is handled per the Privacy Policy, and any unused paid benefits are governed by the then-current paid terms.",
    },
    {
      title: "12. 条款的修改",
      enTitle: "12. Modifications",
      body: "我们可能会不定期更新本条款。更新后的条款将在本页面发布，继续使用本服务即视为您接受修改后的条款。重大变更时，我们会通过网站公告或邮件通知您。",
      enBody:
        "We may update these Terms from time to time. The updated Terms will be posted on this page, and your continued use of the Service constitutes acceptance of the modified Terms. For material changes, we will notify you via website notice or email.",
    },
    {
      title: "13. 适用法律与平台方",
      enTitle: "13. Governing Law and Platform Providers",
      body: "本条款适用中华人民共和国法律。因本条款或服务引起的任何争议，双方应友好协商解决；协商不成的，任何一方均可向本平台运营方所在地有管辖权的人民法院提起诉讼。若您通过 Apple App Store 或 Google Play 等应用商店获取本应用，相关平台方作为本条款的第三方受益人，对其分发行为免责，且本条款不优于您与平台方之间的协议。",
      enBody:
        "These Terms are governed by the laws of the People's Republic of China. Any dispute arising from these Terms or the Service shall first be resolved through friendly negotiation; if unsuccessful, either party may bring a lawsuit to a court with jurisdiction over the operator's location. If you obtained the app via the Apple App Store or Google Play, the relevant platform provider is a third-party beneficiary of these Terms, disclaims liability for distribution, and its terms with you prevail over any conflict.",
    },
    {
      title: "14. 联系我们",
      enTitle: "14. Contact Us",
      body: "如对本服务条款有任何疑问，请通过官网「联系我们」入口或发送邮件至 2740354108@qq.com 与我们联系。",
      enBody:
        "If you have any questions about these Terms, please contact us through the \"Contact Us\" entry on the website or by emailing 2740354108@qq.com.",
    },
  ];

  return (
    <div className="relative min-h-screen overflow-x-clip bg-background text-foreground">
      <header className="fixed top-0 left-0 right-0 z-50 border-b border-white/5 bg-background/80 backdrop-blur-md">
        <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-6">
          <Link to="/" className="flex items-center gap-2.5">
            <span className="flex h-8 w-8 items-center justify-center rounded-xl bg-gradient-to-br from-cyan-400 to-violet-500 shadow-lg shadow-cyan-500/30">
              <Zap className="h-4 w-4 text-white" strokeWidth={2.5} />
            </span>
            <span className="text-base font-bold tracking-tight text-white">
              NEXUS<span className="text-gradient-neon ml-1">LAB</span>
            </span>
          </Link>
          <div className="flex items-center gap-2">
            <div className="inline-flex items-center rounded-full border border-white/10 bg-white/5 p-0.5">
              <button
                onClick={() => setLang("zh")}
                className={`rounded-full px-3 py-1 text-xs font-medium transition-colors ${
                  lang === "zh"
                    ? "bg-gradient-to-r from-cyan-500 to-violet-500 text-white"
                    : "text-muted-foreground hover:text-white"
                }`}
              >
                中文
              </button>
              <button
                onClick={() => setLang("en")}
                className={`rounded-full px-3 py-1 text-xs font-medium transition-colors ${
                  lang === "en"
                    ? "bg-gradient-to-r from-cyan-500 to-violet-500 text-white"
                    : "text-muted-foreground hover:text-white"
                }`}
              >
                EN
              </button>
            </div>
            <Button variant="ghost" size="sm" onClick={() => navigate(-1)} className="gap-1.5 text-muted-foreground hover:text-white">
              <ArrowLeft className="h-4 w-4" />
              {lang === "zh" ? "返回" : "Back"}
            </Button>
          </div>
        </div>
      </header>

      <main className="pt-28 pb-24">
        <div className="mx-auto max-w-3xl px-6">
          <div className="mb-12 text-center">
            <div className="mx-auto mb-5 flex h-14 w-14 items-center justify-center rounded-2xl border border-violet-500/20 bg-violet-500/10 text-violet-400">
              <FileText className="h-7 w-7" />
            </div>
            <h1 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
              {lang === "zh" ? "服务条款" : "Terms of Service"}
            </h1>
            <p className="mt-3 text-sm text-muted-foreground">
              {lang === "zh"
                ? "Terms of Service · 最后更新日期：2026 年 9 月 3 日"
                : "Last updated: September 3, 2026"}
            </p>
          </div>

          <div className="space-y-10 rounded-2xl border border-white/5 bg-card/40 p-8 shadow-2xl sm:p-10">
            {sections.map((section) => (
              <section key={section.title} className="scroll-mt-28">
                <h2 className="mb-2 text-lg font-semibold text-white">
                  {lang === "zh" ? section.title : section.enTitle}
                </h2>
                <p className="leading-relaxed text-muted-foreground">
                  {lang === "zh" ? section.body : section.enBody}
                </p>
              </section>
            ))}
          </div>

          <div className="mt-12 flex flex-col items-center justify-between gap-4 border-t border-white/5 pt-8 text-sm text-muted-foreground sm:flex-row">
            <p>
              {lang === "zh"
                ? "© 2026 NEXUS LAB. 保留所有权利"
                : "© 2026 NEXUS LAB. All rights reserved."}
            </p>
            <div className="flex items-center gap-6">
              <Link to="/privacy" className="transition-colors hover:text-white">
                {lang === "zh" ? "隐私政策" : "Privacy Policy"}
              </Link>
              <Link to="/terms" className="text-white transition-colors hover:text-cyan-300">
                {lang === "zh" ? "服务条款" : "Terms of Service"}
              </Link>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default TermsOfService;
